---
- name: Modify the hostname 
  shell: hostname {{ name | quote }} && echo {{ name | quote }}  > /etc/hostname

#- name: Disable selinux
#  shell: /usr/sbin/setenforce 0

- name: Change SELinux state
# solution-1:
#  shell: sed -i "s/SELINUX=enforcing/SELINUX=disabled/g" /etc/selinux/config && sed -i "s/SELINUXTYPE=targeted/#SELINUXTYPE=targeted/g" /etc/selinux/config warn=False
# solution-2:
#  lineinfile: path=/etc/selinux/config regexp={{ item.regexp }} line={{ item.line }} backup=yes
#  with_items:
#    - {'regexp': '^SELINUX=enforcing', 'line': 'SELINUX=disabled'}
#    - {'regexp': '^SELINUXTYPE=targeted', 'line': '#SELINUXTYPE=targeted'}
# solution-3:
  selinux: state=disabled policy=targeted

#- name: Transfer yum repository to nodes
#  synchronize: src={{ initTempDir }}/{{ item }} dest=/etc/yum.repos.d/{{ item }}
#  with_items:
#    - CentOS-Base.repo
#    - epel.repo

- name: Modify yum repolist
  get_url: url=http://mirrors.aliyun.com/repo/{{ item.url }} dest=/etc/yum.repos.d/{{ item.dest }}
  with_items:
    - { 'url': 'Centos-7.repo', 'dest': 'CentOS-Base.repo' }
    - { 'url': 'epel-7.repo', 'dest': 'epel.repo' }

- name: Install basic package
  yum: name={{ item }} state=present
  with_items:
    - openssl-devel
    - libnl3-devel
    - ipset-devel
    - iptables-devel
    - iptables-services
    - libnfnetlink-devel
    - popt
    - popt-static
    - popt-devel
    - gcc
    - make
    - kernel-headers
    - kernel-devel
    - net-snmp-devel
    - net-tools
    - wget
    - vim
    - sshpass
    - ntp
    - tcpdump
    - nmap-ncat
    - procps-ng
    - bridge-utils
    - lsof
    - tree
    - yum-utils
    - python-chardet
    - python-kitchen
    - device-mapper-persistent-data
    - lvm2
    - audit-libs-python
    - checkpolicy
    - libcgroup
    - libseccomp
    - libsemanage-python 
    - policycoreutils-python
    - python-IPy
    - setools-libs
    - audit
    - audit-libs

- name: Disable Firewalld and NetworkManager
  service: name={{ item.name }} state={{ item.state }} enabled={{ item.enabled }}
  with_items:
    - { 'name': 'firewalld', 'state': 'stopped', 'enabled': 'no' }
    - { 'name': 'iptables', 'state': 'stopped', 'enabled': 'no' }
    - { 'name': 'NetworkManager', 'state': 'stopped', 'enabled': 'no' }
  
#- name: Add hosts
#  shell: echo -e "\n#cmop-registry\n113.142.30.117   cmop-registry" >> /etc/hosts

- name: Transfer ntp.conf to nodes
  template: src={{ initTempDir }}/ntp.conf.j2 dest=/etc/ntp.conf

- name: Restart ntpd
  service: name=ntpd state=restarted enabled=yes
